apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: pac-test-10
  namespace: pipelines-as-code
  # namespace: openshift-pipelines
spec:
  url: "https://github.com/AndrienkoAleksandr/pac-test-10"
  git_provider:
    secret:
      name: "github-webhook-config"
    webhook_secret:
      name: "github-webhook-config"
